services:
  php:
    build: ./back
    command: php -S 0.0.0.0:8000 -t public
    tty: true
    env_file:
      - ./back/.env.local
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8000"
    volumes:
      - ./back:/app
    working_dir: /app
    # environment:
    #   DATABASE_URL: "postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=16&charset=utf8"

  front:
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
  
  quality:
    build: ./docker/quality
    volumes:
      - .:/app
    working_dir: /app
    profiles: ["tools"]

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 10s 
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: