import {
  Activity,
  AlertTriangle,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowLeft,
  ArrowRight,
  Baby,
  BarChart2,
  Bell,
  BellRing,
  Calculator,
  Calendar,
  Check,
  ChevronDown,
  ClipboardCheck,
  Clock,
  Crosshair,
  Crown,
  DoorOpen,
  Edit,
  Eye,
  EyeClosed,
  Flag,
  Flame,
  Ghost,
  Gift,
  Hammer,
  Home,
  Inbox,
  Info,
  KeyRound,
  LineChart,
  Loader2,
  LocateFixed,
  MapPin,
  Maximize2,
  Megaphone,
  PawPrint,
  Plus,
  QrCode,
  Radar,
  Save,
  Scale,
  Search,
  Send,
  Settings2,
  Shield,
  Skull,
  Smartphone,
  Sparkles,
  Sword,
  Swords,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  User2,
  UserCog2,
  UserMinus2,
  Users2,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

export const ICONS = {
  ACTION: <ClipboardCheck size="1em" />,
  ADD: <Plus size="1em" />,
  ALARM: <BellRing size="1em" />,
  ANGEL: <Ghost size="1em" />,
  ARROW_BIG_LEFT: <ArrowBigLeft size="1em" />,
  ARROW_BIG_RIGHT: <ArrowBigRight size="1em" />,
  ARROW_LEFT: <ArrowLeft size="1em" />,
  ARROW_RIGHT: <ArrowRight size="1em" />,
  BADGER: <PawPrint size="1em" />,
  AVERAGE: <LineChart size="1em" />,
  BONUS: <Gift size="1em" />,
  CALCULATOR: <Calculator size="1em" />,
  CALENDAR: <Calendar size="1em" />,
  CANCEL: <X size="1em" />,
  CHECK: <Check size="1em" />,
  CHEVRON_DOWN: <ChevronDown size="1em" />,
  CREATOR: <Hammer size="1em" />,
  CREATE_COMPETITION: <Plus size="1em" />,
  CROWN: <Crown size="1em" />,
  DANGER: <AlertTriangle size="1em" />,
  EDIT: <Edit size="1em" />,
  EMPTY: <Inbox size="1em" />,
  ENTER: <DoorOpen size="1em" />,
  FAILURE: <XCircle size="1em" />,
  FINISHED: <Flag size="1em" />,
  FIRE: <Flame size="1em" />,
  FLAG: <Flag size="1em" />,
  FOG_ACTIVE: <EyeClosed size="1em" />,
  FOG_INACTIVE: <Eye size="1em" />,
  FOG_STATUS: (isActive: boolean) =>
    isActive ? <EyeClosed size="1em" /> : <Eye size="1em" />,
  GAP: <MapPin size="1em" />,
  GHOST: <Ghost size="1em" />,
  EYE: <Eye size="1em" />,
  GUEST_NEW: <Baby size="1em" />,
  HINT: <Info size="1em" />,
  HOME: <Home size="1em" />,
  KARMA: <Scale size="1em" />,
  LINK_PROFILE: <UserCog2 size="1em" />,
  LOADING: <Loader2 size="1em" className="animate-spin" />,
  MAX: <Zap size="1em" />,
  MAX_RECEIVED: <Flame size="1em" />,
  MAX_REPORTED: <Sword size="1em" />,
  MAXIMIZE: <Maximize2 size="1em" />,
  MEDALS: {
    GOLD: <span style={{ fontSize: '1em' }}>🥇</span>,
    SILVER: <span style={{ fontSize: '1em' }}>🥈</span>,
    BRONZE: <span style={{ fontSize: '1em' }}>🥉</span>,
  },
  NOTIFICATION: <Bell size="1em" />,
  NOTIFICATION_ON: <BellRing size="1em" />,
  ONGOING: <Activity size="1em" />,
  PLAYER: <User2 size="1em" />,
  PLAYERS: <Users2 size="1em" />,
  POINTS: <Radar size="1em" />,
  PRECISION: <Crosshair size="1em" />,
  QR: <QrCode size="1em" />,
  RANKING: <BarChart2 size="1em" />,
  REFEREE: <Shield size="1em" />,
  RELATIONS: <Users2 size="1em" />,
  REMOVE_PLAYER: <UserMinus2 size="1em" />,
  REPORTS: <Megaphone size="1em" />,
  ROTATE: <Smartphone size="1em" />,
  SAVE: <Save size="1em" />,
  SEARCH: <Search size="1em" />,
  SECRET: <KeyRound size="1em" />,
  SEND: <Send size="1em" />,
  SETTINGS: <Settings2 size="1em" />,
  STAB: <Swords size="1em" />,
  STARS: <Sparkles size="1em" />,
  START: <DoorOpen size="1em" />,
  STATS: <LineChart size="1em" />,
  SKULL: <Skull size="1em" />,
  SUCCESS: <Check size="1em" />,
  TARGET: <LocateFixed size="1em" />,
  TOOLS: <Wrench size="1em" />,
  TRASH: <Trash2 size="1em" />,
  TRENDING_DOWN: <TrendingDown size="1em" />,
  TRENDING_UP: <TrendingUp size="1em" />,
  TROPHY: <Trophy size="1em" />,
  UPCOMING: <Clock size="1em" />,
  ZAP: <Zap size="1em" />,
} as const;
