export const ICONS = {
  MEDALS: {
    GOLD: '🥇',
    SILVER: '🥈',
    BRONZE: '🥉',
  },
  BADGER: '🦡',
  SECRET: '🔑',
  TRASH: '🗑️',
  DANGER: '⚠️',
  SEARCH: '🔍',
  LOADING: '⏳',
  ONGOING: '🟢',
  UPCOMING: '⌛',
  FINISHED: '🏁',
  HINT: '💡',
  SAVE: '💾',
  ADD: '➕',
  EDIT: '✏️',
  TOOLS: '🛠️',
  STARS: '✨',
  FLAG: '🚩',
  CANCEL: '✕',
  FIRE: '🔥',
  POINTS: '🎯',
  CALENDAR: '📅',
  ALARM: '🚨',
  FOG_STATUS: (isActive: boolean) =>
    isActive ? `${ICONS.FOG_ACTIVE}` : `${ICONS.FOG_INACTIVE}`,
  FOG_ACTIVE: '👻',
  FOG_INACTIVE: '👁️',
  PLAYER: '👤',
  CREATOR: '👑',
  REFEREE: '⚖️',
  GUEST_EYE: '👀',
  GUEST_NEW: '🐣',
  SUCCESS: '✅',
  CHECK: '✓',
  FAILURE: '❌',
  SETTINGS: '⚙️',
  EMPTY: '🏜️',
  CHEVRON_DOWN: '▽',
  HOME: '🏠',
  QR: '📱',
  STAB: '⚔️',
} as const;
