export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  COMPETITIONS: '/competitions',
  COMPETITION_VIEW: '/competitions/:code',
  COMPETITION_PAGE: (code: string) => `/competitions/${code}`,
  API_COMPETITION_GET: (code: string) => `/competitions/by-code/${code}`,
  COMPETITION_LEADERBOARD: (id: string) => `/competitions/${id}/leaderboard`,
  COMPETITION_ACTIONS: (id: string) => `/competitions/${id}/actions`,
  CREATE_COMPETITION: '/admin/competition',
  ADMIN: '/admin',
  PLAYERS: '/players',
  SEARCH_PLAYERS: (query: string) => `/search/players?displayName=${query}`,
  ADD_PLAYERS: (id: string) => `/admin/competition/${id}/add-players`,
};
