# Étape 1 : Build de l'application React
FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# On récupère la clé publique VAPID passée par l'orchestrateur au moment du build
ARG VITE_VAPID_PUBLIC_KEY
ENV VITE_VAPID_PUBLIC_KEY=$VITE_VAPID_PUBLIC_KEY

COPY . .
RUN npm run build

# Étape 2 : Serveur Nginx ultra-léger pour distribuer le Front
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# Configuration pour gérer le Single Page Application (React Router) sans Erreur 404 au rafraîchissement
RUN echo 'server { listen 80; location / { root /usr/share/nginx/html; index index.html; try_files $uri $uri/ /index.html; } }' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]