#!/bin/sh
echo "🐶 Husky vérifie le style du projet..."

# --- Partie BACK-END (PHP) ---
docker compose exec -T php vendor/bin/php-cs-fixer fix src --diff --ansi

# --- Partie FRONT-END (React) ---
# On utilise --loglevel warn pour ne voir que les messages importants
docker compose run --rm quality npx prettier --write front/src --log-level warn

# --- VÉRIFICATION GLOBALE ---
# On demande à Git si des fichiers ont été modifiés (Back ou Front)
git diff --exit-code > /dev/null

if [ $? -ne 0 ]; then
    echo ""
    echo "❌ Le code a été formaté automatiquement (PHP ou React)."
    echo "👉 Vérifie les changements, fais un 'git add .' et recommence ton commit."
    exit 1
fi

echo "✅ Tout est parfait, commit autorisé !"