name: 🚀 Deploy Monorepo to o2switch Prod (ZIP Optimisé)

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # 👈 ICI ON SUPPRIME LE WARNING NODE 20

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Récupération du code
        uses: actions/checkout@v4

      # --- 1. COMPILATION DU FRONT ---
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: 🛠️ Build Frontend
        working-directory: ./front 
        run: |
          npm ci
          npm run build

      # --- 2. PRÉPARATION DU BACK & CRÉATION DU ZIP ---
      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql

      - name: 🛠️ Installation des dépendances et compression ZIP
        working-directory: ./back
        env:
          APP_ENV: prod
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction --no-scripts
          zip -r vendor.zip vendor # 👈 ON COMPRESSE LES 10 000 FICHIERS EN 1 SEUL

      # --- 3. TÉLÉVERSEMENT DES FICHIERS VIA FTP (TRÈS RAPIDE) ---
      - name: 📂 Transfert global vers o2switch via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.O2SWITCH_HOST }}
          username: ${{ secrets.O2SWITCH_USER }}
          password: ${{ secrets.O2SWITCH_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: blaireaudor/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/back/vendor/**
            **/back/var/**
            **/back/.env.local

      # --- 4. EXTRACTION ET COMMANDES FINALES SUR LE SERVEUR ---
      - name: ⚙️ Déclencher l'extraction et les scripts sur o2switch
        run: |
          curl --http1.1 -kfsSL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36" -H "X-Deploy-Secret: ${{ secrets.DEPLOY_SECRET }}" "https://api.blaireaudor.maximerose.com/deploy.php"